name: script-run
on: [push]
env:
  DAY_OF_WEEK: Monday # Setting up job global environment variables in runner
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: |
          sudo bash -f ./.github/scripts/build.sh
        shell: bash
        env:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432 # setting up job local environment variables in runner